version: '3'
services:
  app:
    build: .
    #TODO: ports
    #TODO: - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysq
    container_name: mysql
    ports:
      - "33061:3306"
    expose:
      - "3306"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet
    volumes:
      - ./0001-init.sql:/docker-entrypoint-initdb.d/0001-init.sql
    restart: on-failure