version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      dbuser: test
      dbpass: test
      dbname: pet
      dbhost: mysql-pets
      dbport: 3306
      apikey: testkey
    ports:
     - 8081:8081
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql-pets
    ports:
      - "33061:3306"
    expose:
      - "3306"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet
    volumes:
      - ./0001-init.sql:/docker-entrypoint-initdb.d/0001-init.sql
    restart: on-failure