version: '3'
services:
  app:
    build: .
    #TODO: ports
    #TODO: - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: pet
    restart: on-failure